from multimodal_comms.apps.comma.agents.agent import Agent
import torch
from PIL import Image
from huggingface_hub import login
from transformers import MllamaForConditionalGeneration, AutoProcessor


class LLaVACoTAgent(Agent):
    def __init__(self, role="SOLVER", config = {}) -> None:
        """
        Initialize the agent. Init your model accordingly.
        """
        super(LLaVACoTAgent, self).__init__(role, config)

        model_id = "Xkev/Llama-3.2V-11B-cot"

        self.model = MllamaForConditionalGeneration.from_pretrained(
            model_id,
            torch_dtype=torch.bfloat16,
        ).to(self.device)
        
        self.processor = AutoProcessor.from_pretrained(model_id)


    def respond(self, input_data, actions):
        """
        Respond based on the given conversation history. Return the predicted action.
        Implement model-specific behavior here.

        Args:
            input_data: Data to process (e.g., image, text, etc.).
            actions: Any additional actions to consider when generating the response.
            message: Optional message input.

        Returns:
            predicted_action: The response generated by the model.
        """
        # Implement conversation history string formation here, if needed
        ret = self.get_conversation_history_string(image_data=input_data, actions=actions)
        if type(ret) == tuple:
            image, llm_input = ret
            image = Image.open(image)
            text = "This is a picture of the puzzle manual. " + llm_input
            messages = [
                {"role": "user", "content": [
                    {"type": "image"},
                    {"type": "text", "text": text}
                ]}
            ]
        else:
            image = None
            if input_data != None:
                image = Image.open(input_data)

                messages = [
                    {"role": "user", "content": [
                        {"type": "image"},
                        {"type": "text", "text": ret}
                    ]}
                ]
            else:
                messages = [
                    {"role": "user", "content": [
                        {"type": "text", "text": ret}
                    ]}
                ]

       
        input_text = self.processor.apply_chat_template(messages, add_generation_prompt=True)
        inputs = self.processor(
            image,
            input_text,
            add_special_tokens=False,
            return_tensors="pt"
        ).to(self.device)

        output = self.model.generate(**inputs, max_new_tokens=self.config.get("max_output_len", 1024), do_sample=True, temperature=0.6)
        predicted_action = self.processor.decode(output[0])[len(input_text):].replace("<|eot_id|>", "")
        
        return predicted_action
