from multimodal_comms.apps.comma.agents.agent import Agent
from PIL import Image
from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration
import torch
from qwen_vl_utils import process_vision_info


class OneVisionAgent(Agent):
    def __init__(self, role="SOLVER", config = {}) -> None:
        """
        Initialize the agent. Init your model accordingly.
        """
        super(OneVisionAgent, self).__init__(role, config)

        MODEL_ID = "Fancy-MLLM/R1-Onevision-7B"

        # The default range for the number of visual tokens per image in the model is 4-16384.
        # You can set min_pixels and max_pixels according to your needs, such as a token range of 256-1280, to balance performance and cost.
        min_pixels = 256*28*28
        max_pixels = 256*28*28
        #processor = AutoProcessor.from_pretrained("Qwen/Qwen2.5-VL-7B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)

        self.processor = AutoProcessor.from_pretrained(MODEL_ID, trust_remote_code=True, min_pixels=min_pixels, max_pixels=max_pixels)
        self.model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
            MODEL_ID,
            trust_remote_code=True,
            torch_dtype=torch.bfloat16
        ).to(self.device).eval()

        


    def respond(self, input_data, actions):
        """
        Respond based on the given conversation history. Return the predicted action.
        Implement model-specific behavior here.

        Args:
            input_data: Data to process (e.g., image, text, etc.).
            actions: Any additional actions to consider when generating the response.
            message: Optional message input.

        Returns:
            predicted_action: The response generated by the model.
        """
        # Implement conversation history string formation here, if needed
        ret = self.get_conversation_history_string(image_data=input_data, actions=actions)
        if type(ret) == tuple:
            image, llm_input = ret
            text = "This is a picture of the puzzle manual. " + llm_input
            messages = [
                {"role": "user", "content": [
                    {"type": "image", "image": image},
                    {"type": "text", "text": text}
                ]}
            ]
        else:
            image = None
            if input_data != None:

                messages = [
                    {"role": "user", "content": [
                        {"type": "image", "image": input_data},
                        {"type": "text", "text": ret}
                    ]}
                ]
            else:
                messages = [
                    {"role": "user", "content": [
                        {"type": "text", "text": ret}
                    ]}
                ]


        # messages = [
        #     {
        #         "role": "user",
        #         "content": [
        #             {"type": "image", "image": "<your image path>"},
        #             {"type": "text", "text": "Hint: Please answer the question and provide the final answer at the end. Question: Which number do you have to write in the last daisy?"},
        #         ],
        #     }
        # ]
       
        text = self.processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )

        image_inputs, video_inputs = process_vision_info(messages)
        inputs = self.processor(
            text=[text],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt",
        )
        inputs = inputs.to(self.model.device)

        generated_ids = self.model.generate(**inputs, max_new_tokens=self.config.get("max_output_len", 1024), do_sample=True, temperature=0.6)
        generated_ids_trimmed = [
            out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
        ]
        output_text = self.processor.batch_decode(
            generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )
        #predicted_action = self.processor.decode(output[0])[len(input_text):].replace("<|eot_id|>", "")
        
        return output_text[0].strip()
