from multimodal_comms.apps.comma.agents.agent import Agent

class GenericAgent(Agent):
    def __init__(self, role="AGENT", config={}) -> None:
        """
        Initialize the agent. Init your model accordingly.
        """
        super(GenericAgent, self).__init__(role, config)
        # Initialize your model here, using any configuration settings you specified in the config folder
        # You can then use it in the respond() function below.
        # self.model=...

    def respond(self, image_data, actions):
        """
        Respond based on the given conversation history. Return the predicted action.
        Implement model-specific behavior here.

        Args:
            image_data: Path to the image (None if it is the EXPERT)
            actions: Any additional actions to consider when generating the response.
            message: Optional message input.

        Returns:
            predicted_action: The text response generated by the model.
        """
        # Optionally get the conversation history in a string format using our function
        history = self.get_conversation_history_string(image_data=image_data, actions=actions)
        if type(history) == tuple: # Image of manual is provided (the agent is the EXPERT here)
            # manual image: URL of the image of the manual
            # conversation history: String of the conversation history
            manual_image, conversation_history = history
        else: 
            conversation_history = history
            
            
        # Or you can directly use self.conversation_history, which has the history of
        # past messages between the solver and expert as well as environment feedback
        # conversation_history = process(self.conversation)
        
        # If image_data is not None, you can use it to help with your response here:
        
        # if image_data:
        #     image = Image.open(image_data)


        # Placeholder: Replace with actual input/output handling based on your model
        # model_input = self.preprocess(conversation_history, image, ...)


        # Send request to the model (this is a placeholder, replace with actual logic)
        # For example: response = self.client.chat.completions.create(model_input=model_input)
        # response_text = response.choices[0].message.content

        # Simulate a predicted action (replace with actual model's response)
        # predicted_action = response_text
        
        return predicted_action
